[package]
name = "message-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
libc = "0.2.137"
slotmap = "1.0.6"

[build-dependencies]
cbindgen = "0.24.3"
